language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    # Install Miniconda so we can use it to manage dependencies:
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels ajdawson
    - conda update conda
    - conda info -a
    # Create a conda environment with the base dependencies:
    - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
    - source activate test-environment
    - conda install setuptools nose coverage numpy pyspharm
    # Additional dependencies for Python 2.x:
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
        conda config --add channels SciTools;
        conda install cdat-lite iris;
      fi
    # Install the package:
    - python setup.py install

script:
    # Create an isolated test directory to make sure we test against the
    # installed package rather than the source, which won't work on Python3:
    - mkdir ../test_directory
    - cd ../test_directory
    - nosetests windspharm --verbosity=2 --with-coverage --cover-package=windspharm

notifications:
    email: false
