language: python

python:
  - "2.7"
  - "3.3"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3E5C1192;
        yes | sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable;
        sudo apt-get update;
        sudo apt-get install gfortran python-pip python-scipy python-numpy cython;
        sudo apt-get install libudunits2-dev libhdf5-serial-dev libnetcdf-dev netcdf-bin;
        sudo apt-get install libgeos-dev libproj-dev;
        sudo apt-get install make unzip python-sphinx;
        sudo /usr/bin/pip install --use-mirrors shapely pyshp pep8 mock nose;
        sudo /usr/bin/pip install pyke netCDF4;
        sudo /usr/bin/pip install cdat-lite;
        sudo /usr/bin/pip install coverage;
        mkdir ../prereqs && cd ../prereqs;
        wget http://python-distribute.org/distribute_setup.py;
        sudo /usr/bin/python distribute_setup.py;
        git clone git://github.com/SciTools/cartopy.git;
        cd cartopy;
        git checkout v0.7.0;
        sudo /usr/bin/python setup.py install;
        cd ..;
        git clone git://github.com/SciTools/iris.git;
        cd iris;
        git checkout v1.3.0;
        /usr/bin/python setup.py std_names;
        sudo /usr/bin/python setup.py install;
        cd ..;
        wget http://pyspharm.googlecode.com/files/pyspharm-1.0.8.tar.gz;
        tar xfvz pyspharm-1.0.8.tar.gz;
        cd pyspharm-1.0.8;
        yes | sudo /usr/bin/python setup.py install;
        cd ../../windspharm;
    else
        sudo apt-get install gfortran;
        pip install nose coverage numpy;
        mkdir ../prereqs && cd ../prereqs;
        wget http://pyspharm.googlecode.com/files/pyspharm-1.0.8.tar.gz;
        tar xfvz pyspharm-1.0.8.tar.gz;
        cd pyspharm-1.0.8;
        cp ../../windspharm/.pyspharm.python3.patch py3patch && patch -p0 < py3patch;
        yes | python setup.py install;
        cd ../../windspharm;
    fi


script:
  - if [[ $TRAVIS_PYTHON_VERSION  == 2* ]]; then
        /usr/bin/python setup.py nosetests --verbosity=2 --with-coverage --cover-package=windspharm;
    else
        python setup.py nosetests --verbosity=2 --with-coverage --cover-package=windspharm;
    fi
        

notifications:
  email: false
