language: python

env:
    global:
        - PACKAGES_STANDARD="setuptools pytest pep8 numpy pyspharm"
    matrix:
        - NAME="Python 2.7 (standard)"
          PYTHON_VERSION=2.7
          PACKAGES="${PACKAGES_STANDARD}"
        - NAME="Python 2.7 (metadata)"
          PYTHON_VERSION=2.7
          PACKAGES="${PACKAGES_STANDARD} cdat-lite iris xarray"
        - NAME="Python 3.3 (standard)"
          PYTHON_VERSION=3.3
          PACKAGES="${PACKAGES_STANDARD}"
        - NAME="Python 3.4 (standard)"
          PYTHON_VERSION=3.4
          PACKAGES="${PACKAGES_STANDARD}"
        - NAME="Python 3.4 (metadata)"
          PYTHON_VERSION=3.4
          PACKAGES="${PACKAGES_STANDARD} iris xarray"
        - NAME="Python 3.5 (standard)"
          PYTHON_VERSION=3.5
          PACKAGES="${PACKAGES_STANDARD}"
        - NAME="Python 3.5 (metadata)"
          PYTHON_VERSION=3.5
          PACKAGES="${PACKAGES_STANDARD} xarray"

sudo: false

install:
    # Install Miniconda so we can use it to manage dependencies:
    - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    # Setup conda to use extra channels for dependencies:
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels scitools
    - conda config --add channels ajdawson
    - conda update conda
    - conda info -a
    # Create a conda environment with the required Python version:
    - conda create -n test-environment python=$PYTHON_VERSION
    - source activate test-environment
    # Install required packages:
    - conda install ${PACKAGES}
    # Install the package:
    - python setup.py install

script:
    # Create an isolated test directory to make sure we test against the
    # installed package rather than the source, which won't work on Python3:
    - mkdir ../test_directory
    - cd ../test_directory
    - pytest -vrsx --pyargs windspharm

notifications:
    email: false
